In [19]:
import pandas as pd
from pathlib import Path

In [6]:
df = pd.read_csv("../data/ena_report.tsv", sep = "\t")

In [7]:
df.head()

,run_accession,study_accession,sample_accession,experiment_accession,tax_id,scientific_name,library_name,sample_alias
0,ERR458495,PRJEB5348,SAMEA2400699,ERX424842,4932,Saccharomyces cerevisiae,wild type,wt_sample3
1,ERR458496,PRJEB5348,SAMEA2400699,ERX424843,4932,Saccharomyces cerevisiae,wild type,wt_sample3
2,ERR458501,PRJEB5348,SAMEA2400705,ERX424848,4932,Saccharomyces cerevisiae,mutant,mu_sample2
3,ERR458504,PRJEB5348,SAMEA2400708,ERX424851,4932,Saccharomyces cerevisiae,mutant,mu_sample5
4,ERR458511,PRJEB5348,SAMEA2400715,ERX424858,4932,Saccharomyces cerevisiae,mutant,mu_sample12

In [8]:
df.shape

(672, 8)

In [11]:
run_access = ["ERR458495", "ERR458887", "ERR458882", "ERR458905", "ERR458906", "ERR458921", "ERR458502", "ERR458509", "ERR458517", "ERR458528", "ERR458535", "ERR458552"]
print(len(run_access))

12

In [12]:
df_subsampled = df[df["run_accession"].isin(run_access)]

In [14]:
df_subsampled

,run_accession,study_accession,sample_accession,experiment_accession,tax_id,scientific_name,library_name,sample_alias
0,ERR458495,PRJEB5348,SAMEA2400699,ERX424842,4932,Saccharomyces cerevisiae,wild type,wt_sample3
130,ERR458502,PRJEB5348,SAMEA2400706,ERX424849,4932,Saccharomyces cerevisiae,mutant,mu_sample3
132,ERR458509,PRJEB5348,SAMEA2400713,ERX424856,4932,Saccharomyces cerevisiae,mutant,mu_sample10
133,ERR458517,PRJEB5348,SAMEA2400721,ERX424864,4932,Saccharomyces cerevisiae,mutant,mu_sample18
134,ERR458528,PRJEB5348,SAMEA2400732,ERX424875,4932,Saccharomyces cerevisiae,mutant,mu_sample29
136,ERR458535,PRJEB5348,SAMEA2400739,ERX424882,4932,Saccharomyces cerevisiae,mutant,mu_sample36
137,ERR458552,PRJEB5348,SAMEA2400756,ERX424899,4932,Saccharomyces cerevisiae,mutant,mu_sample53
344,ERR458882,PRJEB5348,SAMEA2401091,ERX425229,4932,Saccharomyces cerevisiae,wild type,wt_sample12
345,ERR458887,PRJEB5348,SAMEA2401096,ERX425234,4932,Saccharomyces cerevisiae,wild type,wt_sample17
346,ERR458905,PRJEB5348,SAMEA2401114,ERX425252,4932,Saccharomyces cerevisiae,wild type,wt_sample35
347,ERR458906,PRJEB5348,SAMEA2401115,ERX425253,4932,Saccharomyces cerevisiae,wild type,wt_sample36
349,ERR458921,PRJEB5348,SAMEA2401130,ERX425268,4932,Saccharomyces cerevisiae,wild type,wt_sample51

In [ ]:
assert len(df_subsampled) == 12
assert df_subsampled.library_name.value_counts().to_dict() == {"wild type": 6, "mutant": 6}
assert df_subsampled.run_accession.is_unique

In [24]:
df = df_subsampled
df.to_csv("../data/ena_report.tsv", index=False)